"""
Curated Korean recipe dataset.
Spoonacular's Korean coverage is limited, so we maintain our own
high-quality set that gets blended into search results.
"""

KOREAN_RECIPES = [
    {
        "id": "kr-1",
        "title": "Kimchi Jjigae (Kimchi Stew)",
        "image": None,
        "emoji": "\ud83c\udf72",
        "readyInMinutes": 30,
        "servings": 4,
        "pricePerServing": 2.50,
        "cuisines": ["Korean"],
        "diets": ["dairy-free"],
        "summary": "A deeply warming, spicy stew made with aged kimchi, tofu, and pork belly. The quintessential Korean comfort food that tastes better the next day.",
        "nutrition": {
            "calories": 320,
            "protein": 22,
            "carbs": 18,
            "fat": 20,
            "fiber": 4,
        },
        "ingredients": [
            {"name": "Aged kimchi", "amount": "2 cups", "price": 2.50},
            {"name": "Pork belly (sliced thin)", "amount": "6 oz", "price": 3.00},
            {"name": "Firm tofu", "amount": "1 block (14 oz)", "price": 2.00},
            {"name": "Gochugaru (red pepper flakes)", "amount": "1 tbsp", "price": 0.30},
            {"name": "Garlic", "amount": "4 cloves", "price": 0.40},
            {"name": "Green onions", "amount": "3 stalks", "price": 0.40},
            {"name": "Sesame oil", "amount": "1 tsp", "price": 0.20},
            {"name": "Rice", "amount": "2 cups", "price": 1.20},
        ],
        "steps": [
            "Slice pork belly into bite-sized pieces. Cut tofu into 1-inch cubes.",
            "In a pot, sauté pork belly until fat renders, about 3 minutes.",
            "Add chopped kimchi and its juice. Cook for 5 minutes, stirring.",
            "Add 3 cups water, gochugaru, and minced garlic. Bring to a boil.",
            "Reduce heat and simmer 15 minutes until flavors meld.",
            "Add tofu cubes, simmer 5 more minutes. Don't stir too much — tofu breaks.",
            "Finish with sesame oil and sliced green onions. Serve bubbling hot with rice.",
        ],
    },
    {
        "id": "kr-2",
        "title": "Bibimbap",
        "image": None,
        "emoji": "\ud83c\udf5a",
        "readyInMinutes": 40,
        "servings": 4,
        "pricePerServing": 3.00,
        "cuisines": ["Korean"],
        "diets": [],
        "summary": "Colorful rice bowl topped with seasoned vegetables, a fried egg, and spicy gochujang sauce. Beautiful, nutritious, and endlessly customizable.",
        "nutrition": {
            "calories": 480,
            "protein": 18,
            "carbs": 65,
            "fat": 16,
            "fiber": 6,
        },
        "ingredients": [
            {"name": "Rice", "amount": "2 cups", "price": 1.20},
            {"name": "Spinach", "amount": "4 oz", "price": 1.50},
            {"name": "Bean sprouts", "amount": "1 cup", "price": 0.80},
            {"name": "Carrots", "amount": "2 medium", "price": 0.60},
            {"name": "Zucchini", "amount": "1 medium", "price": 0.80},
            {"name": "Eggs", "amount": "4 large", "price": 1.20},
            {"name": "Gochujang", "amount": "3 tbsp", "price": 0.60},
            {"name": "Sesame oil", "amount": "2 tbsp", "price": 0.40},
            {"name": "Soy sauce", "amount": "2 tbsp", "price": 0.30},
            {"name": "Garlic", "amount": "3 cloves", "price": 0.30},
            {"name": "Sesame seeds", "amount": "1 tbsp", "price": 0.20},
        ],
        "steps": [
            "Cook rice and keep warm.",
            "Blanch spinach and bean sprouts separately (30 sec each). Squeeze dry.",
            "Season spinach with sesame oil, garlic, and salt. Do the same for sprouts.",
            "Julienne carrots and zucchini. Sauté each separately with a little oil and salt.",
            "Fry eggs sunny-side up, keeping yolks runny.",
            "Assemble: rice in bowl, arrange each vegetable in sections on top.",
            "Top with fried egg and a generous spoonful of gochujang. Mix everything together before eating.",
        ],
    },
    {
        "id": "kr-3",
        "title": "Japchae (Glass Noodle Stir-Fry)",
        "image": None,
        "emoji": "\ud83c\udf5d",
        "readyInMinutes": 35,
        "servings": 4,
        "pricePerServing": 2.80,
        "cuisines": ["Korean"],
        "diets": ["dairy-free"],
        "summary": "Chewy sweet potato glass noodles with colorful vegetables in a savory-sweet soy sesame sauce. A Korean party staple.",
        "nutrition": {
            "calories": 380,
            "protein": 12,
            "carbs": 58,
            "fat": 12,
            "fiber": 4,
        },
        "ingredients": [
            {"name": "Sweet potato glass noodles (dangmyeon)", "amount": "8 oz", "price": 3.00},
            {"name": "Spinach", "amount": "3 oz", "price": 1.00},
            {"name": "Carrots", "amount": "1 large", "price": 0.40},
            {"name": "Bell pepper", "amount": "1 medium", "price": 1.00},
            {"name": "Onion", "amount": "1 medium", "price": 0.50},
            {"name": "Mushrooms", "amount": "4 oz", "price": 1.50},
            {"name": "Soy sauce", "amount": "3 tbsp", "price": 0.45},
            {"name": "Sugar", "amount": "1.5 tbsp", "price": 0.10},
            {"name": "Sesame oil", "amount": "2 tbsp", "price": 0.40},
            {"name": "Garlic", "amount": "3 cloves", "price": 0.30},
            {"name": "Sesame seeds", "amount": "1 tbsp", "price": 0.20},
        ],
        "steps": [
            "Cook glass noodles according to package (usually 6-7 min). Drain, rinse, and cut with scissors.",
            "Toss noodles with 1 tbsp soy sauce, 1 tbsp sugar, and 1 tbsp sesame oil.",
            "Julienne all vegetables. Sauté each separately with a pinch of salt — keep them crisp.",
            "Blanch spinach, squeeze dry, and season with sesame oil.",
            "Combine everything in a large bowl. Add remaining soy sauce, sugar, sesame oil, and minced garlic.",
            "Toss thoroughly with hands or tongs. Sprinkle with sesame seeds.",
            "Serve warm or at room temperature. Great as a side or main.",
        ],
    },
    {
        "id": "kr-4",
        "title": "Bulgogi (Korean BBQ Beef)",
        "image": None,
        "emoji": "\ud83e\udd69",
        "readyInMinutes": 25,
        "servings": 4,
        "pricePerServing": 3.50,
        "cuisines": ["Korean"],
        "diets": ["dairy-free", "gluten-free"],
        "summary": "Thin-sliced marinated beef, sweet and savory with pear and soy. The most famous Korean dish for good reason.",
        "nutrition": {
            "calories": 420,
            "protein": 32,
            "carbs": 28,
            "fat": 22,
            "fiber": 2,
        },
        "ingredients": [
            {"name": "Beef sirloin or ribeye (sliced thin)", "amount": "1.5 lbs", "price": 8.00},
            {"name": "Soy sauce", "amount": "4 tbsp", "price": 0.60},
            {"name": "Asian pear or apple", "amount": "1/2", "price": 0.75},
            {"name": "Brown sugar", "amount": "2 tbsp", "price": 0.15},
            {"name": "Sesame oil", "amount": "2 tbsp", "price": 0.40},
            {"name": "Garlic", "amount": "5 cloves", "price": 0.50},
            {"name": "Ginger", "amount": "1 inch piece", "price": 0.30},
            {"name": "Onion", "amount": "1 medium", "price": 0.50},
            {"name": "Green onions", "amount": "4 stalks", "price": 0.50},
            {"name": "Rice", "amount": "2 cups", "price": 1.20},
        ],
        "steps": [
            "Blend pear, soy sauce, brown sugar, sesame oil, garlic, and ginger into a marinade.",
            "Slice beef very thin (freezing 30 min first helps). Toss with marinade.",
            "Marinate at least 30 minutes, or up to overnight in the fridge.",
            "Slice onion into rings. Heat a skillet or grill pan over high heat.",
            "Cook beef and onions in batches — don't overcrowd or it steams instead of searing.",
            "Cook 2-3 minutes per side until caramelized.",
            "Garnish with sliced green onions and sesame seeds. Serve over rice.",
        ],
    },
    {
        "id": "kr-5",
        "title": "Sundubu Jjigae (Soft Tofu Stew)",
        "image": None,
        "emoji": "\ud83e\udd58",
        "readyInMinutes": 20,
        "servings": 2,
        "pricePerServing": 2.50,
        "cuisines": ["Korean"],
        "diets": ["dairy-free"],
        "summary": "Silky soft tofu in a fiery, savory broth. Served bubbling in a stone pot, it's pure Korean soul food.",
        "nutrition": {
            "calories": 280,
            "protein": 20,
            "carbs": 15,
            "fat": 16,
            "fiber": 3,
        },
        "ingredients": [
            {"name": "Soft (silken) tofu", "amount": "1 tube (16 oz)", "price": 2.00},
            {"name": "Gochugaru", "amount": "1.5 tbsp", "price": 0.40},
            {"name": "Garlic", "amount": "3 cloves", "price": 0.30},
            {"name": "Onion", "amount": "1/2 medium", "price": 0.25},
            {"name": "Zucchini", "amount": "1/2 medium", "price": 0.40},
            {"name": "Eggs", "amount": "2", "price": 0.60},
            {"name": "Sesame oil", "amount": "1 tbsp", "price": 0.20},
            {"name": "Green onions", "amount": "2 stalks", "price": 0.25},
            {"name": "Soy sauce", "amount": "1 tbsp", "price": 0.15},
            {"name": "Rice", "amount": "1 cup", "price": 0.60},
        ],
        "steps": [
            "Heat sesame oil in a small pot. Sauté diced onion until softened.",
            "Add gochugaru and minced garlic, stir for 30 seconds.",
            "Add 2 cups water (or anchovy broth for deeper flavor) and soy sauce. Bring to a boil.",
            "Slide in the soft tofu, breaking it gently into large chunks with a spoon.",
            "Add sliced zucchini. Simmer 5 minutes.",
            "Crack eggs directly into the bubbling stew. Cover for 1 minute.",
            "Top with green onions and serve immediately with rice.",
        ],
    },
    {
        "id": "kr-6",
        "title": "Tteokbokki (Spicy Rice Cakes)",
        "image": None,
        "emoji": "\ud83c\udf36\ufe0f",
        "readyInMinutes": 20,
        "servings": 3,
        "pricePerServing": 2.00,
        "cuisines": ["Korean"],
        "diets": ["vegan", "dairy-free"],
        "summary": "Chewy rice cakes in a sweet-spicy gochujang sauce. Korea's most beloved street food snack.",
        "nutrition": {
            "calories": 350,
            "protein": 8,
            "carbs": 68,
            "fat": 5,
            "fiber": 2,
        },
        "ingredients": [
            {"name": "Korean rice cakes (tteok)", "amount": "1 lb", "price": 3.00},
            {"name": "Gochujang", "amount": "2.5 tbsp", "price": 0.50},
            {"name": "Gochugaru", "amount": "1 tbsp", "price": 0.30},
            {"name": "Sugar", "amount": "1 tbsp", "price": 0.05},
            {"name": "Soy sauce", "amount": "1 tbsp", "price": 0.15},
            {"name": "Garlic", "amount": "2 cloves", "price": 0.20},
            {"name": "Green onions", "amount": "2 stalks", "price": 0.25},
            {"name": "Fish cake (eomuk)", "amount": "4 oz", "price": 1.50},
        ],
        "steps": [
            "If rice cakes are frozen or dried, soak in water for 30 minutes first.",
            "Combine 2 cups water, gochujang, gochugaru, soy sauce, sugar, and minced garlic in a pan.",
            "Bring to a boil over medium heat, stirring to dissolve the paste.",
            "Add rice cakes and sliced fish cakes. Cook 8-10 minutes, stirring frequently.",
            "The sauce will thicken as it reduces — keep stirring so it doesn't stick.",
            "When rice cakes are soft and chewy and sauce is glossy, remove from heat.",
            "Top with sliced green onions. Serve hot — they firm up as they cool.",
        ],
    },
    {
        "id": "kr-7",
        "title": "Kimchi Bokkeumbap (Kimchi Fried Rice)",
        "image": None,
        "emoji": "\ud83c\udf5a",
        "readyInMinutes": 15,
        "servings": 2,
        "pricePerServing": 1.80,
        "cuisines": ["Korean"],
        "diets": ["dairy-free"],
        "summary": "The ultimate fridge-cleanup meal. Tangy kimchi, day-old rice, and a fried egg on top — 15 minutes, done.",
        "nutrition": {
            "calories": 420,
            "protein": 14,
            "carbs": 62,
            "fat": 14,
            "fiber": 3,
        },
        "ingredients": [
            {"name": "Cooked rice (day-old)", "amount": "3 cups", "price": 0.90},
            {"name": "Kimchi (chopped)", "amount": "1 cup", "price": 1.50},
            {"name": "Eggs", "amount": "2", "price": 0.60},
            {"name": "Gochujang", "amount": "1 tbsp", "price": 0.20},
            {"name": "Sesame oil", "amount": "1 tbsp", "price": 0.20},
            {"name": "Vegetable oil", "amount": "1 tbsp", "price": 0.10},
            {"name": "Green onions", "amount": "2 stalks", "price": 0.25},
            {"name": "Sesame seeds", "amount": "For garnish", "price": 0.10},
        ],
        "steps": [
            "Heat vegetable oil in a large skillet or wok over high heat.",
            "Add chopped kimchi, stir-fry 2-3 minutes until slightly caramelized.",
            "Add cold rice, breaking up clumps. Stir-fry 3-4 minutes.",
            "Add gochujang and sesame oil, toss until everything is evenly coated and rice is hot.",
            "Push rice to the side, fry eggs sunny-side up in the same pan.",
            "Plate rice, top with fried egg. Garnish with green onions and sesame seeds.",
        ],
    },
    {
        "id": "kr-8",
        "title": "Doenjang Jjigae (Soybean Paste Stew)",
        "image": None,
        "emoji": "\ud83c\udf72",
        "readyInMinutes": 25,
        "servings": 3,
        "pricePerServing": 2.20,
        "cuisines": ["Korean"],
        "diets": ["dairy-free"],
        "summary": "Earthy, rich soybean paste stew with vegetables and tofu. Korea's answer to miso soup, but heartier.",
        "nutrition": {
            "calories": 260,
            "protein": 16,
            "carbs": 22,
            "fat": 12,
            "fiber": 5,
        },
        "ingredients": [
            {"name": "Doenjang (Korean soybean paste)", "amount": "2.5 tbsp", "price": 0.60},
            {"name": "Firm tofu", "amount": "1/2 block", "price": 1.00},
            {"name": "Zucchini", "amount": "1 small", "price": 0.60},
            {"name": "Potato", "amount": "1 small", "price": 0.40},
            {"name": "Onion", "amount": "1/2 medium", "price": 0.25},
            {"name": "Garlic", "amount": "3 cloves", "price": 0.30},
            {"name": "Green onions", "amount": "2 stalks", "price": 0.25},
            {"name": "Gochugaru", "amount": "1 tsp", "price": 0.15},
            {"name": "Rice", "amount": "1.5 cups", "price": 0.90},
        ],
        "steps": [
            "Dice potato, zucchini, onion, and tofu into bite-sized cubes.",
            "Bring 3 cups water (or anchovy/kelp broth) to a boil.",
            "Dissolve doenjang into the broth — use a spoon to press it through a strainer for smoothness.",
            "Add potato and onion first. Boil 5 minutes until potato starts to soften.",
            "Add zucchini, tofu, gochugaru, and minced garlic. Simmer 8 minutes.",
            "Taste and adjust — add more doenjang if needed.",
            "Top with green onions and serve with rice.",
        ],
    },
    {
        "id": "kr-9",
        "title": "Gyeran-bap (Egg Rice)",
        "image": None,
        "emoji": "\ud83c\udf73",
        "readyInMinutes": 10,
        "servings": 1,
        "pricePerServing": 1.00,
        "cuisines": ["Korean"],
        "diets": ["dairy-free", "gluten-free"],
        "summary": "The simplest Korean meal: hot rice, a raw egg stirred in, sesame oil and soy sauce. 5 minutes, $1, pure comfort.",
        "nutrition": {
            "calories": 380,
            "protein": 14,
            "carbs": 52,
            "fat": 12,
            "fiber": 1,
        },
        "ingredients": [
            {"name": "Hot cooked rice", "amount": "1.5 cups", "price": 0.45},
            {"name": "Egg", "amount": "1 large", "price": 0.30},
            {"name": "Soy sauce", "amount": "1 tbsp", "price": 0.15},
            {"name": "Sesame oil", "amount": "1 tsp", "price": 0.15},
            {"name": "Butter (optional)", "amount": "1 tsp", "price": 0.10},
            {"name": "Sesame seeds", "amount": "Pinch", "price": 0.05},
            {"name": "Green onion", "amount": "1 stalk", "price": 0.15},
        ],
        "steps": [
            "Make sure rice is freshly cooked and very hot — it needs to partially cook the egg.",
            "Place hot rice in a bowl. Make a well in the center.",
            "Crack egg directly into the well. Add butter if using.",
            "Drizzle soy sauce and sesame oil over everything.",
            "Mix vigorously until egg is coated throughout and rice looks glossy.",
            "Top with sesame seeds and sliced green onion.",
        ],
    },
    {
        "id": "kr-10",
        "title": "Kongnamul Guk (Soybean Sprout Soup)",
        "image": None,
        "emoji": "\ud83e\udd62",
        "readyInMinutes": 20,
        "servings": 3,
        "pricePerServing": 1.20,
        "cuisines": ["Korean"],
        "diets": ["vegan", "dairy-free", "gluten-free"],
        "summary": "Light, clean, and refreshing. Known as Korea's hangover cure, but perfect as an everyday soup.",
        "nutrition": {
            "calories": 180,
            "protein": 10,
            "carbs": 20,
            "fat": 6,
            "fiber": 4,
        },
        "ingredients": [
            {"name": "Soybean sprouts", "amount": "8 oz", "price": 1.50},
            {"name": "Garlic", "amount": "3 cloves", "price": 0.30},
            {"name": "Green onions", "amount": "3 stalks", "price": 0.40},
            {"name": "Gochugaru", "amount": "1 tsp", "price": 0.15},
            {"name": "Soy sauce", "amount": "1 tbsp", "price": 0.15},
            {"name": "Salt", "amount": "To taste", "price": 0.05},
            {"name": "Sesame oil", "amount": "1 tsp", "price": 0.15},
            {"name": "Rice", "amount": "1.5 cups", "price": 0.90},
        ],
        "steps": [
            "Rinse soybean sprouts thoroughly. Trim any brown tails.",
            "Add sprouts and 4 cups water to a pot. Do NOT open the lid once you start — sprouts get beany if exposed.",
            "Bring to a boil, then simmer covered for 10 minutes.",
            "Add minced garlic, gochugaru, soy sauce, and salt.",
            "Simmer 3 more minutes.",
            "Add sesame oil and sliced green onions. Serve hot with rice.",
        ],
    },
]
